# Generated by Django 3.0.6 on 2020-05-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='achs_sel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achs_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='herb_sel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pres_sel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres_title', models.CharField(max_length=50)),
            ],
        ),
    ]
