# Generated by Django 3.0.6 on 2020-05-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herb', '0002_achs_sel_herb_sel_pres_sel'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_open',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('files', models.FileField(blank=True, null=True, upload_to='up_file', verbose_name='上传文件')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
            },
        ),
    ]
